version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: job_discovery_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: job_discovery
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - job_discovery_network

  # Redis for Celery
  redis:
    image: redis:7-alpine
    container_name: job_discovery_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - job_discovery_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: job_discovery_backend
    restart: unless-stopped
    environment:
      MONGODB_URL: mongodb://admin:password123@mongodb:27017/job_discovery?authSource=admin
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: your-secret-key-change-in-production
      PYTHONPATH: /app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
    depends_on:
      - mongodb
      - redis
    networks:
      - job_discovery_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.new
    container_name: job_discovery_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - job_discovery_network

volumes:
  mongodb_data:
  redis_data:

networks:
  job_discovery_network:
    driver: bridge